/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.JogadorController;
import Model.Jogador;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.plaf.BorderUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import java.awt.ComponentOrientation;
import java.awt.Cursor;
import javax.swing.border.EmptyBorder;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.ListSelectionModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author leanddro
 */
public class Ranking extends javax.swing.JFrame {
    /**
     * Creates new form Ranking
     */
    public Ranking() {
        initComponents();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<Jogador> jogadores = JogadorController.rankiar();

        int posicao = 1;
        for (Jogador jogador : jogadores) {
            model.addRow(new Object[]{posicao, jogador.getApelido(), jogador.getTempo()});
            posicao++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jTable1.setShowGrid(false);
		jTable1.setFocusable(false);
		jTable1.setFillsViewportHeight(true);
		jTable1.setBorder(new EmptyBorder(0, 0, 0, 0));
		jTable1.setIntercellSpacing(new Dimension(0, 0));
		jTable1.setFont(new Font("Tahoma", Font.PLAIN, 13));
		jTable1.setGridColor(Color.WHITE);
		jTable1.setShowVerticalLines(false);
		jTable1.setRowMargin(3);
		jTable1.setRowHeight(25);
		btn_Ok = new javax.swing.JButton();
		btn_Ok.setForeground(Color.BLACK);
		btn_Ok.setFocusable(false);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Ranking");
		setMinimumSize(new Dimension(800,600));
		setLocation(600, 150);
		getContentPane().setBackground(Color.WHITE);
		
		//CORES----------------------------
		Color SelectColor = new Color(232,57, 95);
		Color headerColor = new Color (32,136,203);
		//
		Border borda = BorderFactory.createMatteBorder(0, 0,0,0, Color.WHITE);
		Border bordaButtonVoltar = BorderFactory.createMatteBorder(1, 1,1,1,headerColor);
		Border bordaButtonVoltarHover = BorderFactory.createMatteBorder(1, 1,1,1, SelectColor);
		//---------------------------------
		jScrollPane1.setBorder(borda);
		//BTN ESTILO
		btn_Ok.setCursor(new Cursor(Cursor.HAND_CURSOR));
		btn_Ok.setBounds(30, 30, 50, 30);
		btn_Ok.setBorder(bordaButtonVoltar);
		btn_Ok.setContentAreaFilled(false);
		btn_Ok.setForeground(headerColor);
		btn_Ok.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseEntered(MouseEvent e) {
				btn_Ok.setBorder(bordaButtonVoltarHover);
				btn_Ok.setForeground(SelectColor);
			}
			@Override
			public void mouseExited(MouseEvent e) {
				btn_Ok.setForeground(headerColor);
				btn_Ok.setBorder(bordaButtonVoltar);
			}
		});
		//HEADER TABLLE
		JTableHeader header = jTable1.getTableHeader();
		header.setReorderingAllowed(false);
		header.setFont(new Font("Roboto Light", Font.PLAIN, 18));
		header.setOpaque(true);
		header.isBackgroundSet();
		header.setBorder(borda);
		header.setResizingAllowed(true);
		header.setBackground(headerColor);
		header.setForeground(Color.WHITE);
		//BODY TABLE
		jTable1.setBackground(Color.WHITE);
		jTable1.setSelectionBackground(SelectColor);
		jTable1.setSelectionForeground(Color.WHITE);
		//
		jTable1.setModel(new DefaultTableModel(
			new Object[][] {
			},
			new String[] {
				"Posi\u00E7\u00E3o", "Apelido", "Tempo"
			}
		));
		jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		jScrollPane1.setViewportView(jTable1);

		btn_Ok.setText("VOLTAR");
		btn_Ok.addActionListener(new ActionListener() {
			
			
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
				Principal.menu.setVisible(true);
			}
		});
		
		
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap(703, Short.MAX_VALUE)
					.addComponent(btn_Ok)
					.addContainerGap())
				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addComponent(btn_Ok)
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

	// Variables declaration - do not modify                     
	private javax.swing.JButton btn_Ok;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
}
